# DigitalOcean App Platform 설정
name: cargolink-auction
region: sgp
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/cargo_link  # 이 부분은 실제 GitHub 저장소로 변경 필요
    branch: main
  run_command: bundle exec puma -C config/puma.rb
  environment_slug: ruby-on-rails
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  health_check:
    http_path: /up
  envs:
  - key: RAILS_ENV
    value: production
  - key: RAILS_MASTER_KEY
    type: SECRET
    value: bedab7b024e6455ee014c2b83ad2e723
  - key: DATABASE_URL
    type: SECRET
    value: YOUR_DATABASE_URL  # DigitalOcean에서 자동 설정됨
  - key: REDIS_URL  
    type: SECRET
    value: YOUR_REDIS_URL  # DigitalOcean에서 자동 설정됨

# 데이터베이스 설정
databases:
- name: cargolink-db
  engine: PG
  version: "15"
  size: basic
  num_nodes: 1

# Redis 캐시 설정  
- name: cargolink-redis
  engine: REDIS
  version: "7"
  size: basic
  num_nodes: 1

# 백그라운드 작업 처리 (Sidekiq)
workers:
- name: sidekiq
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/cargo_link
    branch: main
  run_command: bundle exec sidekiq
  environment_slug: ruby-on-rails
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: RAILS_ENV
    value: production
  - key: RAILS_MASTER_KEY
    type: SECRET
    value: bedab7b024e6455ee014c2b83ad2e723